#!/bin/sh
### BEGIN INIT INFO
# Provides:          webcamserver 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: webcamserver daemon
# Description: Watch video from your webcam on android app
### END INIT INFO

daemon_name="webcamserver"

get_pid() {
        pid=`pidof $daemon_name`
        echo $pid
}

start_daemon() {

        pid=$(get_pid)
        if [ $pid ]; then
                echo "daemon already running with pid: $pid"
        else
                echo "starting daemon..."
                /usr/bin/$daemon_name 
                pid=$(get_pid)
                echo "daemon started with pid: $pid"
        fi
}

stop_daemon() {

        pid=$(get_pid)
        echo $pid
        if [ $pid ]; then
                echo "killing daemon with pid: $pid"
                kill -9 $pid
        else
                echo "process is not alive..." 
        fi
}

reload_daemon() {
        echo "reloading daemon..."
}


case "$1" in
        start)
                start_daemon;;
        stop)
                stop_daemon;;
        reload)
                reload_daemon;;
        *)
                echo "usage: /etc/init.d/webcamserver start|stop|reload"
esac
